all: frameWithProcessEventC.o Main.hs TechnicalUtils.hs FrameWithProcessEvent.hs Messages.hs
	ghc.exe -optl-s -O2 Main.hs frameWithProcessEventC.o -lstdc++

frameWithProcessEvent.o: frameWithProcessEvent.cpp frameWithProcessEvent.h
	gcc.exe -c -O2 frameWithProcessEvent.cpp `wx-config --cflags` -o frameWithProcessEventC.o

